# Generated by Django 5.0.1 on 2024-01-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='sum_paid',
            new_name='payment_sum',
        ),
    ]
