# Generated by Django 5.0.1 on 2024-01-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название урока'),
        ),
    ]
